export const IpcChannels = {
  GetAppVersion: "app:get-version",
  AutomationAnalyzeNow: "automation:analyze-now",
  ServicesActivate: "services:activate",
  ServicesGetStatus: "services:get-status",
  ModelTestConnection: "model:test-connection",
  ModelListProviders: "model:list-providers",
  ModelSetProvider: "model:set-provider",
  SettingsGet: "settings:get",
  SettingsUpdate: "settings:update",
  ObsGetStatus: "obs:get-status",
  ModelMonitorStart: "model-monitor:start",
  ModelMonitorStop: "model-monitor:stop",
  ModelMonitorStatus: "model-monitor:status",
  ModelMonitorEvent: "model-monitor:event",
  VtsGetStatus: "vts:get-status",
  VtsConnect: "vts:connect",
  VtsDisconnect: "vts:disconnect",
  VtsAuthenticate: "vts:authenticate",
  VtsGetHotkeys: "vts:get-hotkeys",
  VtsGetCatalog: "vts:get-catalog",
  VtsRefreshCatalog: "vts:refresh-catalog",
  VtsUpdateCatalogOverride: "vts:update-catalog-override",
  VtsUpdateCueLabels: "vts:update-cue-labels",
  VtsTriggerHotkey: "vts:trigger-hotkey",
  CaptureStart: "capture:start",
  CaptureStop: "capture:stop",
  CaptureStatus: "capture:status",
  CaptureStatusLite: "capture:status-lite",
  CaptureListSources: "capture:list-sources",
  CaptureExportClip: "capture:export-clip",
  CaptureControl: "capture:control",
  CaptureFrame: "capture:frame",
  CaptureAudio: "capture:audio",
  CaptureClip: "capture:clip",
  CaptureLevel: "capture:level",
  CaptureError: "capture:error",
} as const;

export type IpcChannel = typeof IpcChannels[keyof typeof IpcChannels];
