export const VTS_CUE_LABEL_VALUES = [
  "greeting",
  "wave",
  "happy",
  "excited",
  "laughing",
  "evil_laugh",
  "smug",
  "angry",
  "frustrated",
  "shocked",
  "surprised",
  "sad",
  "crying",
  "cute_reaction",
  "love_reaction",
  "confused",
  "embarrassed",
  "sleepy",
  "dramatic_moment",
  "magic_moment",
  "hype_moment",
  "idle",
  "manual_request",
  "unknown",
] as const;
